[package]
name = "rust-optimal-transport"
version = "0.1.0"
authors = ["kachark <kkachar@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
nalgebra = "0.29.0"
ordered-float = "2.5.1"

[build-dependencies]
cxx-build = "1.0"
